# -*- coding: utf-8 -*-
"""ReversePDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knfFmCsdLmwhBETy8QV6hhhwXQ1ZLhNx
"""

!pip install pypdf

from pypdf import PdfReader, PdfWriter
import os

# Assumes CS.pdf is already in /content/ (visible in Files panel)
input_pdf = "CS.pdf"

if not os.path.exists(input_pdf):
    print(f"File not found: {input_pdf}")
else:
    try:
        reader = PdfReader(input_pdf)
        writer = PdfWriter()

        # Reverse pages
        for page_num in range(len(reader.pages) - 1, -1, -1):
            writer.add_page(reader.pages[page_num])

        output_pdf = "CS_reversed.pdf"
        with open(output_pdf, 'wb') as out:
            writer.write(out)

        print(f"Saved: {output_pdf}")

        # Optional: Download it
        from google.colab import files
        files.download(output_pdf)

    except Exception as e:
        print(f"Error: {e}")